export const content = {
  home: {
    hero: {
      title: "Capturamos el tipo de recuerdos que se vuelven más valiosos con el tiempo",
      subtitle: "En Arrebol Weddings contamos historias de amor que ya llevan un camino recorrido. No vemos la boda como un inicio, sino como la consolidación de todo lo que han vivido juntos.",
      cta1: "Ver nuestra galería",
      cta2: "Agendar una llamada",
    },
    about: {
      title: "Recuerdos para toda la vida",
      text: "Su boda es mucho más que un compromiso; es la celebración de una historia de amor que está a punto de comenzar un nuevo capítulo. En cada mirada, en cada sonrisa y en cada lágrima de felicidad, hay un momento que merece ser guardado para siempre.\n\nNos apasiona contar historias a través de nuestras cámaras y formar parte de uno de los días más importantes de sus vidas. Cada detalle, desde los preparativos hasta la última canción de la noche, refleja la esencia de su amor.\n\nQueremos que cuando miren atrás, cada imagen los transporte a esos momentos mágicos. Para nosotros, capturar su historia es una forma de honrar la belleza de ese día, dejando una huella imborrable que durará toda la vida.",
    },
    values: [
      {
        title: "Los recuerdos envejecen hermoso",
        description: "Creemos en un estilo que resista modas pasajeras para que sus fotos y videos se sigan viendo actuales dentro de muchos años.",
      },
      {
        title: "Momentos que fluyen",
        description: "No forzamos poses incómodas. Buscamos que todo suceda con naturalidad y que la emoción sea genuina.",
      },
      {
        title: "Acompañamiento cercano",
        description: "Desde la primera llamada hasta la entrega final, estamos presentes para responder dudas, calmar nervios y ayudarles a disfrutar el proceso.",
      },
    ],
    stories: {
      title: "Algunas de las historias que hemos tenido la dicha de contar",
      subtitle: "Cada boda es distinta, pero en todas buscamos lo mismo: que se reconozcan a ustedes mismos cuando se vean en sus recuerdos.",
      featured: [
        { couple: "María & Carlos", venue: "Hacienda San Antonio, Querétaro" },
        { couple: "Andrea & Roberto", venue: "Casa de Piedra, San Miguel de Allende" },
        { couple: "Sofía & Daniel", venue: "Viñedos La Redonda, Guanajuato" },
        { couple: "Valeria & Alejandro", venue: "Hotel Matilda, San Miguel de Allende" },
        { couple: "Fernanda & Luis", venue: "Rancho Las Sabinas, Guanajuato" },
        { couple: "Paola & Miguel", venue: "Hacienda Sepúlveda, Querétaro" },
      ],
    },
    process: {
      title: "Así trabajamos",
      steps: [
        {
          title: "Primera conversación",
          description: "Nos conocemos, nos cuentan su historia y resolvemos todas sus dudas.",
        },
        {
          title: "Planeación y acompañamiento",
          description: "Revisamos el timeline de la boda, definimos prioridades y coordinamos con su planner o venue.",
        },
        {
          title: "El día de la boda",
          description: "Llegamos antes, trabajamos discretamente y buscamos siempre la mejor luz y los momentos más significativos.",
        },
      ],
    },
    testimonials: {
      title: "Lo que dicen las parejas\nque han confiado en nosotros",
      items: [
        {
          quote: "No tenemos palabras para agradecer la gozada que fue trabajar con ustedes. Desde un inicio se mostraron accesibles, amables y super profesionales. Tener el video y las fotos con ustedes garantizó que nuestros recuerdos queden para siempre, justo como los imaginábamos. Gracias por todo el tiempo para planear esto, por la sesión y los videos del save the date que todo el mundo chuleó.",
          author: "Cris",
        },
        {
          quote: "Desde el día que los contactamos tuvimos la atención impecable, totalmente profesionales y más que recomendables!",
          author: "Karen",
        },
        {
          quote: "Anthony y Brenda son muy buenas personas y fotógrafos. Hicieron que nuestro evento fuera especial. En todo momento fueron sumamente amables y flexibles. Altamente recomendables.",
          author: "Andrea",
        },
        {
          quote: "Anthony y Brenda capturaron nuestra boda de una forma increíble y muy profesional además que son unos seres maravillosos. Mucho talento!",
          author: "Carolina",
        },
        {
          quote: "Sinceramente me sorprendió tanto profesionalismo, atención y flexibilidad. Quedamos más que satisfechas con las fotografías y video!! SIN DUDA recomiendo ampliamente a Anthony!!",
          author: "Yetzy",
        },
        {
          quote: "Anthony capturó nuestra boda y superó todas nuestras expectativas. Desde todas las fotos hasta el video, Arrebol se superó a sí mismo. Son profesionales, amables e increíblemente talentosos. Recomiendo encarecidamente usar Arrebol para sus fotos de boda/compromiso!",
          author: "Valeria",
        },
        {
          quote: "No se van a arrepentir nunca! Puntuales, alegres, te es muy fácil posar naturalmente, las fotos con excelente calidad, atentos! Estamos muy felices con su trabajo y de haberlos contratado, sin duda lo haré para otro evento que tenga.",
          author: "Paula",
        },
        {
          quote: "El equipo de Arrebol fue sumamente claro y profesional en todo momento. Estuvieron atentos todo el tiempo, nos hicieron sentir muy bien durante la sesión y las fotos quedaron preciosas, igual que el álbum. Estamos viendo de vernos de nuevo por aniversario!",
          author: "Guadalupe",
        },
        {
          quote: "Anthony y Brenda son muy buenas personas y fotógrafos. Hicieron que nuestro evento fuera especial. En todo momento fueron sumamente amables y flexibles.",
          author: "Andrick",
        },
        {
          quote: "Mi boda fue en Temixco, yo soy de otro estado y siempre fueron atentos y accesibles. Increíbles fotos y video, parece una película. La calidad de nuestras fotos no tiene comparación, gran trabajo de su equipo. Gracias Arrebol.",
          author: "Brenda",
        },
        {
          quote: "Working with Arrebol was an absolute dream! The photos are stunning and tell our story perfectly.",
          author: "Jonathan",
        },
        {
          quote: "From the engagement shoot to the wedding day, they made us feel so comfortable and captured every special moment beautifully.",
          author: "Tory",
        },
      ],
    },
    finalCta: {
      title: "¿Les gustaría que contemos su historia?",
      subtitle: "Escríbannos para revisar su fecha, conocer sus planes y construir juntos el recuerdo de ese día.",
      button: "Ir a contacto",
    },
  },
  galeria: {
    title: "Galería",
    subtitle: "Una muestra de las historias que hemos contado",
    intro: "Aquí pueden ver un poco de nuestro trabajo en distintos venues, estilos de boda y horarios. Cada pareja tiene su propio ritmo, su propia luz y su propia forma de amar. Nuestro trabajo es encontrarla.",
    images: [
      "AyJ-109.webp",
      "AyJ-149.webp",
      "AyJ-394.webp",
      "AyJ-447.webp",
      "AyJ-493.webp",
      "AyJ-93.webp",
      "aym-76.webp",
      "aym-84.webp",
      "CyD-21.webp",
      "CyD-23.webp",
      "CyD-24.webp",
      "CyD-28.webp",
      "CyD-38.webp",
      "CyD-42.webp",
      "CyD-49.webp",
      "CyD-52.webp",
      "CyD-65.webp",
      "CyD-68.webp",
      "CyD-69.webp",
      "CyD-75.webp",
      "CyD-80.webp",
      "CyD-82.webp",
      "CyD-86.webp",
      "K&E-102.webp",
      "K&E-145.webp",
      "K&E-151.webp",
      "K&E-157.webp",
      "K&E-337.webp",
      "K&E-430.webp",
      "K&E-474.webp",
      "KyB-1.webp",
      "KyB-235.webp",
      "KyB-285.webp",
      "KyB-304.webp",
      "KyB-463.webp",
      "KyB-564.webp",
      "KyB-607.webp",
      "PyC-174.webp",
      "PyC-259.webp",
      "PyC-275.webp",
      "PyC-59.webp",
      "PyP-110.webp",
      "PyP-128.webp",
      "PyP-14.webp",
      "PyP-154.webp",
      "PyP-370.webp",
      "PyP-395.webp",
      "PyP-432.webp",
      "PyP-535.webp",
      "PyP-80.webp",
      "PyP-91.webp",
      "R&K-102.webp",
      "R&K-112.webp",
      "R&K-76.webp",
      "R&K-84.webp",
      "Sofía-y-Pablo-118.webp",
      "Sofía-y-Pablo-276.webp",
      "Sofía-y-Pablo-286.webp",
      "Sofía-y-Pablo-452.webp",
      "SyD-96.webp",
      "SYO-209.webp",
      "SYO-221.webp",
      "SYO-532.webp",
      "SYO-574.webp",
      "SYO-654.webp",
      "SYO-716.webp",
      "SYO-726.webp",
      "SYO-736.webp",
      "SYO-792.webp",
      "SYO-796.webp",
      "SYO-832.webp",
      "SyP-109.webp",
      "SyP-217.webp",
      "SyP-273.webp",
      "T&M-115.webp",
      "T&M-188.webp",
      "T&M-643.webp",
      "TOP-AyJ-178.webp",
      "TOP-AyJ-500.webp",
      "TOP-CyD-41.webp",
      "TOP-CyD-67.webp",
      "TOP-KyB-23.webp",
      "TOP-KyB-236.webp",
      "TOP-MG1228.webp",
      "TOP-PyC-312.webp",
      "TOP-PyP-505.webp",
      "TOP-SyD-125.webp",
      "TOP-SyD-162.webp",
      "TOP-SyP-116.webp",
      "TOP-SyP-324.webp",
      "_MG_0739.webp",
      "_MG_0967.webp",
      "_MG_1134.webp",
      "_MG_1174.webp",
      "_MG_1308.webp",
      "_MG_1430.webp",
      "_MG_1471.webp",
    ],
  },
  proceso: {
    title: "El proceso",
    subtitle: "De la primera llamada a la entrega final",
    intro: "Nos gusta que todo esté claro desde el inicio. Estas son las etapas que recorreremos juntos y lo que pueden esperar en cada una.",
    steps: [
      {
        title: "Primera llamada",
        description: "Platicamos sobre su boda, su historia, qué les gusta y qué no. Revisamos disponibilidad de fecha y resolvemos dudas sobre paquetes, tiempos y forma de trabajo.",
      },
      {
        title: "Firma de contrato y apartado de fecha",
        description: "Una vez que deciden avanzar, firmamos un contrato claro y sencillo, y con el anticipo su fecha queda oficialmente reservada.",
      },
      {
        title: "Reunión de planeación",
        description: "Unas semanas antes de la boda revisamos el timeline detallado: horarios, sedes, personas importantes, momentos clave y cualquier sorpresa que estén planeando.",
      },
      {
        title: "El día de la boda",
        description: "Llegamos con tiempo, nos coordinamos con su planner y el venue, y comenzamos a trabajar de forma discreta. Mezclamos una mirada documental con ciertos momentos guiados para asegurar retratos que atesoren.",
      },
      {
        title: "Selección y edición",
        description: "Después de la boda, hacemos una curaduría cuidadosa. Editamos cada imagen y construimos la narrativa del video para que todo tenga continuidad emocional.",
      },
      {
        title: "Entrega",
        description: "Entregamos en una galería online privada y, dependiendo del paquete, en USB, álbum impreso o caja personalizada. Nuestro objetivo es que la experiencia de ver sus recuerdos sea tan especial como el día en sí.",
      },
    ],
  },
  paquetes: {
    title: "Paquetes",
    subtitle: "Colecciones de fotografía y video para contar su boda de principio a fin",
    intro: "Nuestras colecciones están pensadas para adaptarse a distintos tipos de boda: desde celebraciones íntimas en una sola locación, hasta grandes eventos en múltiples sedes y varios días. Todas incluyen fotografía y video, así como una curaduría cuidadosa de cada momento.",
    collections: [
      {
        name: "Colección Uno",
        features: [
          "8 horas de cobertura",
          "1 fotógrafo",
          "400–500 fotografías",
          "Galería digital",
          "1 videógrafo",
          "Video de 20–30 minutos",
          "Versión 1 minuto",
          'Photobook 8.5x11" (50 páginas)',
        ],
        price: "$49,000 MXN",
        description: "Ideal para bodas íntimas en una sola ubicación, capturando los preparativos, la ceremonia y la recepción. Diseñada para resaltar los momentos más especiales y la conexión personal de celebraciones con hasta 150 invitados.",
      },
      {
        name: "Colección Dos",
        features: [
          "10 horas de cobertura",
          "1 fotógrafo",
          "600–700 fotografías",
          "Galería digital",
          "2 videógrafos",
          "Video de 30–40 minutos",
          "Versión 3–5 minutos",
          "Versión 1 minuto",
          'Photobook 8.5x11" (50 páginas)',
        ],
        price: "$59,000 MXN",
        description: "Diseñada para una cobertura integral de bodas en una o varias locaciones, capturando cada detalle del día. Desde los preparativos hasta los momentos más espectaculares. Incluye una sesión previa que pueden usar para fotos casuales, el civil, rehearsal dinner o cualquier otro momento especial.",
      },
      {
        name: "Colección Tres",
        features: [
          "12 horas de cobertura",
          "1 fotógrafo",
          "800–900 fotografías",
          "Galería digital",
          "1 videógrafo",
          "Video de 50–60 minutos",
          "Versión 3–5 minutos",
          "Versión 1 minuto",
          'Photobook 11x11" (50 páginas)',
          "Sesión pre boda",
          "Sesión post boda",
        ],
        price: "$69,000 MXN",
        description: "Ideal para bodas que se celebran en múltiples locaciones o durante varios días. Particularmente adecuada para una cobertura extendida de la fiesta. Incluye una sesión previa y otra posterior, que pueden utilizarse con el propósito que ustedes deseen. Cada momento se captura para tener un recuerdo extendido de todos los aspectos de su celebración.",
      },
      {
        name: "Colección Diamante",
        features: [
          "12 horas de cobertura",
          "2 fotógrafos",
          "1000+ fotografías",
          "Galería digital",
          "2 videógrafos",
          "Video de 45–60 minutos",
          "Versión 3–5 minutos",
          "Versión 1 minuto",
          "Creador de contenido (reels & photos)",
          "Dron para tomas aéreas",
          'Photobook 12x12" (75 páginas)',
          "Print box (50 fotografías)",
          "Sesión pre boda",
          "Sesión post boda",
        ],
        price: "$79,000 MXN",
        description: "Diseñada para celebrar en grande, con cobertura en múltiples locaciones. Con sesiones antes y después de la boda. Cada detalle se captura desde múltiples ángulos, permitiendo una visión dinámica y precisa. Recomendada para grandes celebraciones con más de 300 invitados y para la cobertura dirigida a redes sociales.",
      },
    ],
    customNote: "Si su boda tiene características muy específicas (bodas destino, celebraciones de varios días, eventos íntimos fuera de la ciudad), podemos ajustar cualquiera de estas colecciones o crear una propuesta a la medida. Escríbannos y lo diseñamos juntos.",
  },
  contacto: {
    title: "Contacto",
    subtitle: "Cuéntenos sobre su boda",
    intro: "Queremos saber más sobre ustedes. Todos los detalles nos ayudarán a plasmar mejor su día.",
    fields: {
      couple: "Nombre de la pareja",
      email: "Correo electrónico",
      phone: "Teléfono",
      date: "Fecha tentativa de la boda",
      venue: "Lugar / venue (si ya lo tienen)",
      guests: "Número aproximado de invitados",
      source: "Cómo nos conocieron",
      message: "Mensaje",
    },
    sourceOptions: [
      "Instagram",
      "Recomendación",
      "Planner",
      "Búsqueda en Google",
      "Otro",
    ],
    disclaimer: "Respondemos personalmente cada mensaje y procuramos hacerlo en menos de 24–48 horas. Si no reciben respuesta, revisen su carpeta de spam o escríbannos directamente a: hola@arrebolweddings.com",
  },
  footer: {
    tagline: "Recuerdos que se vuelven más valiosos con el tiempo",
    email: "hola@arrebolweddings.com",
    instagram: "@arrebolweddings",
    copyright: "© 2025 Arrebol Weddings. Todos los derechos reservados.",
    note: "Porque las mejores historias merecen ser contadas con cuidado.",
  },
};
