export const contentEs = {
  common: {
    menu: "MEN├Ü",
    close: "CERRAR",
    viewMore: "Ver m├ís",
    loading: "Cargando...",
    goToContact: "Ir a contacto",
    navigation: {
      home: "HOME",
      gallery: "GALER├ìA",
      process: "EL PROCESO",
      collections: "COLECCIONES",
      blog: "BLOG",
      contact: "CONTACTO",
    },
    cookieAlert: {
      message: "Utilizamos cookies para asegurar que tengas la mejor experiencia en nuestro sitio web.",
      button: "Aceptar",
    },
    privacyPolicy: {
      title: "Pol├¡tica de Privacidad",
      content: "Contenido de la pol├¡tica de privacidad...",
    },
  },
  home: {
    hero: {
      taglinePart1: "RECUERDOS",
      taglinePart2: "que duran por",
      taglinePart3: "GENERACIONES",
      title: "Capturamos el tipo de recuerdos que se vuelven m├ís valiosos con el tiempo",
      subtitle: "En Arrebol Weddings contamos historias de amor que ya llevan un camino recorrido. No vemos la boda como un inicio, sino como la consolidaci├│n de todo lo que han vivido juntos.",
      cta1: "Ver nuestra galer├¡a",
      cta2: "Agendar una llamada",
    },
    about: {
      title: "Recuerdos para toda la vida",
      text: "Su boda es mucho m├ís que un compromiso; es la celebraci├│n de una historia de amor que est├í a punto de comenzar un nuevo cap├¡tulo. En cada mirada, en cada sonrisa y en cada l├ígrima de felicidad, hay un momento que merece ser guardado para siempre.\n\nNos apasiona contar historias a trav├®s de nuestras c├ímaras y formar parte de uno de los d├¡as m├ís importantes de sus vidas. Cada detalle, desde los preparativos hasta la ├║ltima canci├│n de la noche, refleja la esencia de su amor.\n\nQueremos que cuando miren atr├ís, cada imagen los transporte a esos momentos m├ígicos. Para nosotros, capturar su historia es una forma de honrar la belleza de ese d├¡a, dejando una huella imborrable que durar├í toda la vida.",
      quote: "Capturamos el tipo de im├ígenes que se vuelven m├ís valiosos con el tiempo",
    },
    philosophy: {
      line1: "Somos instantes que pasan, im├ígenes que traen nostalgia.",
      line2: "Alg├║n d├¡a seremos recuerdo, y la foto y el video ser├ín el eco m├ís fiel de lo que fuimos:",
      line3: "la forma m├ís sencilla de volver a un momento que ya no est├í.",
    },
    values: [
      {
        title: "Los recuerdos envejecen hermoso",
        description: "Creemos en un estilo que resista modas pasajeras para que sus fotos y videos se sigan viendo actuales dentro de muchos a├▒os.",
      },
      {
        title: "Momentos que fluyen",
        description: "No forzamos poses inc├│modas. Buscamos que todo suceda con naturalidad y que la emoci├│n sea genuina.",
      },
      {
        title: "Acompa├▒amiento cercano",
        description: "Desde la primera llamada hasta la entrega final, estamos presentes para responder dudas, calmar nervios y ayudarles a disfrutar el proceso.",
      },
    ],
    stories: {
      title: "Algunas de las historias que hemos tenido la dicha de contar",
      subtitle: "Cada boda es distinta, pero en todas buscamos lo mismo: que se reconozcan a ustedes mismos cuando se vean en sus recuerdos.",
      viewStory: "Ver historia",
      featured: [
        { couple: "Mar├¡a & Carlos", venue: "Hacienda San Antonio, Quer├®taro" },
        { couple: "Andrea & Roberto", venue: "Casa de Piedra, San Miguel de Allende" },
        { couple: "Sof├¡a & Daniel", venue: "Vi├▒edos La Redonda, Guanajuato" },
        { couple: "Valeria & Alejandro", venue: "Hotel Matilda, San Miguel de Allende" },
        { couple: "Fernanda & Luis", venue: "Rancho Las Sabinas, Guanajuato" },
        { couple: "Paola & Miguel", venue: "Hacienda Sep├║lveda, Quer├®taro" },
      ],
    },
    process: {
      title: "As├¡ trabajamos",
      steps: [
        {
          title: "Primera conversaci├│n",
          description: "Nos conocemos, nos cuentan su historia y resolvemos todas sus dudas.",
        },
        {
          title: "Planeaci├│n y acompa├▒amiento",
          description: "Revisamos el timeline de la boda, definimos prioridades y coordinamos con su planner o venue.",
        },
        {
          title: "El d├¡a de la boda",
          description: "Llegamos antes, trabajamos discretamente y buscamos siempre la mejor luz y los momentos m├ís significativos.",
        },
      ],
    },
    testimonials: {
      title: "Lo que dicen las parejas\nque han confiado en nosotros",
      items: [
        {
          quote: "No tenemos palabras para agradecer la gozada que fue trabajar con ustedes. Desde un inicio se mostraron accesibles, amables y super profesionales. Tener el video y las fotos con ustedes garantiz├│ que nuestros recuerdos queden para siempre, justo como los imagin├íbamos. Gracias por todo el tiempo para planear esto, por la sesi├│n y los videos del save the date que todo el mundo chule├│.",
          author: "Cris",
        },
        {
          quote: "Desde el d├¡a que los contactamos tuvimos la atenci├│n impecable, totalmente profesionales y m├ís que recomendables!",
          author: "Karen",
        },
        {
          quote: "Anthony y Brenda son muy buenas personas y fot├│grafos. Hicieron que nuestro evento fuera especial. En todo momento fueron sumamente amables y flexibles. Altamente recomendables.",
          author: "Andrea",
        },
        {
          quote: "Anthony y Brenda capturaron nuestra boda de una forma incre├¡ble y muy profesional adem├ís que son unos seres maravillosos. Mucho talento!",
          author: "Carolina",
        },
        {
          quote: "Sinceramente me sorprendi├│ tanto profesionalismo, atenci├│n y flexibilidad. Quedamos m├ís que satisfechas con las fotograf├¡as y video!! SIN DUDA recomiendo ampliamente a Brenda y Anthony!!",
          author: "Yetzy",
        },
        {
          quote: "Anthony captur├│ nuestra boda y super├│ todas nuestras expectativas. Desde todas las fotos hasta el video, Arrebol se super├│ a s├¡ mismo. Son profesionales, amables e incre├¡blemente talentosos. Recomiendo encarecidamente usar Arrebol para sus fotos de boda/compromiso!",
          author: "Valeria",
        },
        {
          quote: "No se van a arrepentir nunca! Puntuales, alegres, te es muy f├ícil posar naturalmente, las fotos con excelente calidad, atentos! Estamos muy felices con su trabajo y de haberlos contratado, sin duda lo har├® para otro evento que tenga.",
          author: "Paula",
        },
        {
          quote: "El equipo de Arrebol fue sumamente claro y profesional en todo momento. Estuvieron atentos todo el tiempo, nos hicieron sentir muy bien durante la sesi├│n y las fotos quedaron preciosas, igual que el ├ílbum. Estamos viendo de vernos de nuevo por aniversario!",
          author: "Guadalupe",
        },
        {
          quote: "Anthony y Brenda son muy buenas personas y fot├│grafos. Hicieron que nuestro evento fuera especial. En todo momento fueron sumamente amables y flexibles.",
          author: "Andrick",
        },
        {
          quote: "Mi boda fue en Temixco, yo soy de otro estado y siempre fueron atentos y accesibles. Incre├¡bles fotos y video, parece una pel├¡cula. La calidad de nuestras fotos no tiene comparaci├│n, gran trabajo de su equipo. Gracias Arrebol.",
          author: "Brenda",
        },
        {
          quote: "Working with Arrebol was an absolute dream! The photos are stunning and tell our story perfectly.",
          author: "Jonathan",
        },
        {
          quote: "From the engagement shoot to the wedding day, they made us feel so comfortable and captured every special moment beautifully.",
          author: "Tory",
        },
      ],
    },
    finalCta: {
      title: "┬┐Les gustar├¡a que contemos su historia?",
      subtitle: "Escr├¡bannos para revisar su fecha, conocer sus planes y construir juntos el recuerdo de ese d├¡a.",
      button: "Ir a contacto",
      whatsappIntro: "O escr├¡benos directamente por WhatsApp:",
      whatsappButton: "Contactar por WhatsApp",
      whatsappMessage: "┬íHola! Deseo m├ís informaci├│n sobre sus servicios de fotograf├¡a y video",
    },
  },
  galeria: {
    title: "Galer├¡a",
    subtitle: "Una muestra de las historias que hemos contado",
    intro: "Aqu├¡ pueden ver un poco de nuestro trabajo en distintos venues, estilos de boda y horarios. Cada pareja tiene su propio ritmo, su propia luz y su propia forma de amar. Nuestro trabajo es encontrarla.",
    viewFullGallery: "Ver galer├¡a completa",
    loading: "Cargando galer├¡a...",
    whatsappText: "La manera m├ís r├ípida de contactarnos es a trav├®s de WhatsApp ┬íNo dudes en escribirnos!",
    whatsappButton: "Contactar por WhatsApp",
    whatsappMessage: "┬íHola! Deseo m├ís informaci├│n sobre sus servicios de fotograf├¡a y video",
    filters: {
      all: "TODO",
      photos: "FOTOGRAF├ìAS",
      clips: "CLIPS",
    },
    picTime: {
      text: "Explora nuestras galer├¡as completas de bodas en nuestra plataforma de entrega de fotos, donde encontrar├ís cientos de im├ígenes de cada celebraci├│n.",
      button: "Ver galer├¡as completas en Pic-Time",
    },
    vidflow: {
      text: "Conoce c├│mo entregamos los videos a nuestras parejas. Esta galer├¡a muestra un ejemplo completo con todas las versiones finales.",
      button: "Ver galer├¡a completa en Vidflow",
    },
    combined: {
      text: "Explora nuestras galer├¡as completas de bodas. Cada pareja recibe su galer├¡a de fotos en Pic-Time y su entrega de video en Vidflow.",
      picTimeButton: "Ver fotos en Pic-Time",
      vidflowButton: "Ver videos en Vidflow",
    },
    images: [
      "AyJ-109.webp",
      "AyJ-149.webp",
      "AyJ-394.webp",
      "AyJ-447.webp",
      "AyJ-493.webp",
      "AyJ-93.webp",
      "aym-76.webp",
      "aym-84.webp",
      "CyD-21.webp",
      "CyD-24.webp",
      "CyD-38.webp",
      "CyD-42.webp",
      "CyD-49.webp",
      "CyD-52.webp",
      "CyD-65.webp",
      "CyD-69.webp",
      "CyD-75.webp",
      "CyD-80.webp",
      "CyD-82.webp",
      "KandE-102.webp",
      "KandE-145.webp",
      "KandE-151.webp",
      "KandE-157.webp",
      "KandE-337.webp",
      "KandE-430.webp",
      "KandE-474.webp",
      "KyB-1.webp",
      "KyB-235.webp",
      "KyB-285.webp",
      "KyB-304.webp",
      "KyB-463.webp",
      "KyB-564.webp",
      "KyB-607.webp",
      "PyC-174.webp",
      "PyC-259.webp",
      "PyC-275.webp",
      "PyC-59.webp",
      "PyP-110.webp",
      "PyP-128.webp",
      "PyP-14.webp",
      "PyP-154.webp",
      "PyP-370.webp",
      "PyP-395.webp",
      "PyP-432.webp",
      "PyP-535.webp",
      "PyP-80.webp",
      "RandK-102.webp",
      "RandK-112.webp",
      "RandK-76.webp",
      "RandK-84.webp",
      "Sof├¡a-y-Pablo-118.webp",
      "Sof├¡a-y-Pablo-276.webp",
      "Sof├¡a-y-Pablo-286.webp",
      "Sof├¡a-y-Pablo-452.webp",
      "SyD-96.webp",
      "SYO-221.webp",
      "SYO-532.webp",
      "SYO-654.webp",
      "SYO-716.webp",
      "SYO-726.webp",
      "SYO-792.webp",
      "SYO-796.webp",
      "SYO-832.webp",
      "SyP-109.webp",
      "SyP-217.webp",
      "SyP-273.webp",
      "TandM-115.webp",
      "TandM-188.webp",
      "TandM-643.webp",
      "TOP-AyJ-178.webp",
      "TOP-AyJ-500.webp",
      "TOP-CyD-41.webp",
      "TOP-CyD-67.webp",
      "TOP-KyB-23.webp",
      "TOP-KyB-236.webp",
      "TOP-MG1228.webp",
      "TOP-PyC-312.webp",
      "TOP-PyP-505.webp",
      "TOP-SyD-125.webp",
      "TOP-SyD-162.webp",
      "TOP-SyP-116.webp",
      "TOP-SyP-324.webp",
      "_MG_0739.webp",
      "_MG_0967.webp",
      "_MG_1134.webp",
      "_MG_1174.webp",
      "_MG_1308.webp",
      "_MG_1430.webp",
      "_MG_1471.webp",
      "SandJ-207.webp",
      "SandJ-214.webp",
      "SandJ-404.webp",
      "SandJ-414.webp",
      "SandJ-857.webp",
    ],
  },
  proceso: {
    title: "El proceso",
    subtitle: "De la primera llamada a la entrega final",
    intro: "Nos gusta que todo est├® claro desde el inicio. Estas son las etapas que recorreremos juntos y lo que pueden esperar en cada una.",
    steps: [
      {
        title: "Primera llamada",
        description: "Platicamos a detalle sobre su boda, su historia y la esencia de lo que imaginan para ese d├¡a. Nos cuentan qu├® les gusta, qu├® prefieren evitar y cu├íles son los momentos que consideran m├ís importantes. Tambi├®n revisamos la disponibilidad de la fecha y resolvemos todas sus dudas sobre paquetes, coberturas, tiempos y nuestra forma de trabajar. Es una conversaci├│n cercana y sencilla, pensada para empezar a entender su estilo y lo que buscan en sus recuerdos.",
      },
      {
        title: "Firma de contrato y apartado de fecha",
        description: "Una vez que deciden avanzar, formalizamos la reserva con un contrato claro, sencillo y sin letras peque├▒as. Para asegurar su fecha, se realiza un anticipo del 30%, con lo cual queda oficialmente apartado en nuestro calendario. Desde ese momento, ustedes pueden relajarse: nosotros llevamos el control de tiempos y los mantenemos informados en cada etapa.",
      },
      {
        title: "Reuni├│n de planeaci├│n",
        description: "Unas semanas antes de la boda, revisamos juntos el timeline detallado: horarios, sedes, clima estimado, personas importantes, momentos clave y cualquier sorpresa o din├ímica especial que est├®n preparando. Este paso nos permite anticiparnos a lo que ocurrir├í y asegurarnos de que cada instante significativo quede registrado sin estr├®s ni improvisaciones.",
      },
      {
        title: "El d├¡a de la boda",
        description: "Llegamos con tiempo y nos coordinamos con su wedding planner, con el venue y con los proveedores involucrados. Trabajamos de manera discreta, sin interrumpir y sin forzar situaciones. Nuestra mirada es principalmente documental, pero tambi├®n guiamos ciertos momentos para asegurar retratos naturales, con buena luz y que realmente reflejen qui├®nes son. Ustedes solo tienen que vivir su d├¡a; nosotros nos encargamos del resto.",
      },
      {
        title: "Selecci├│n y edici├│n",
        description: "Despu├®s de la boda, realizamos una curadur├¡a cuidadosa en la que seleccionamos las mejores im├ígenes, aquellas que cuentan la historia con emoci├│n y coherencia. Cada fotograf├¡a se edita una por una siguiendo un estilo atemporal. En paralelo, construimos la narrativa del video para que fluya y evoque el d├¡a completo, no solo los momentos principales.",
      },
      {
        title: "Entrega",
        description: "Preparamos una galer├¡a online donde podr├ín ver, descargar y compartir su material. Dependiendo del paquete, tambi├®n reciben ├ílbum impreso o caja con impresiones. Nuestro objetivo es que la experiencia de entrega sea tan especial como la boda misma: limpia, ordenada y dise├▒ada para que disfruten sus recuerdos todas las veces que quieran.",
      },
    ],
    whatsappText: "┬┐Listo para comenzar? Cont├íctanos por WhatsApp para agendar una videollamada.",
    whatsappButton: "Contactar por WhatsApp",
    whatsappMessage: "┬íHola! Deseo m├ís informaci├│n sobre sus servicios de fotograf├¡a y video",
  },
  colecciones: {
    title: "Colecciones",
    subtitle: "Fotograf├¡a y video para contar su boda de principio a fin",
    intro: "Nuestras colecciones est├ín pensadas para adaptarse a distintos tipos de boda: desde celebraciones ├¡ntimas en una sola locaci├│n, hasta grandes eventos en m├║ltiples sedes y varios d├¡as. Todas incluyen fotograf├¡a y video, as├¡ como una curadur├¡a cuidadosa de cada momento.",
    collections: [
      {
        name: "Colecci├│n Uno",
        features: [
          "8 horas de cobertura",
          "1 fot├│grafo",
          "400ÔÇô500 fotograf├¡as",
          "Galer├¡a digital",
          "1 vide├│grafo",
          "Video de 20ÔÇô30 minutos",
          "Versi├│n 1 minuto",
          'Photobook 8.5x11" (50 p├íginas)',
        ],
        price: "$49,000 MXN",
        description: "Ideal para bodas ├¡ntimas en una sola ubicaci├│n, capturando los preparativos, la ceremonia y la recepci├│n. Dise├▒ada para resaltar los momentos m├ís especiales y la conexi├│n personal de celebraciones con hasta 150 invitados.",
      },
      {
        name: "Colecci├│n Dos",
        features: [
          "10 horas de cobertura",
          "1 fot├│grafo",
          "600ÔÇô700 fotograf├¡as",
          "Galer├¡a digital",
          "1 vide├│grafo",
          "Video de 30ÔÇô40 minutos",
          "Versi├│n 3ÔÇô5 minutos",
          "Versi├│n 1 minuto",
          'Photobook 8.5x11" (50 p├íginas)',
          "Sesi├│n pre boda",
        ],
        price: "$59,000 MXN",
        description: "Dise├▒ada para una cobertura integral de bodas en una o varias locaciones, capturando cada detalle del d├¡a. Desde los preparativos hasta los momentos m├ís espectaculares. Incluye una sesi├│n previa que pueden usar para fotos casuales, el civil, rehearsal dinner o cualquier otro momento especial.",
      },
      {
        name: "Colecci├│n Tres",
        features: [
          "12 horas de cobertura",
          "1 fot├│grafo",
          "800ÔÇô900 fotograf├¡as",
          "Galer├¡a digital",
          "1 vide├│grafo",
          "Video de 50ÔÇô60 minutos",
          "Versi├│n 3ÔÇô5 minutos",
          "Versi├│n 1 minuto",
          'Photobook 11x11" (50 p├íginas)',
          "Sesi├│n pre boda",
          "Sesi├│n post boda",
        ],
        price: "$69,000 MXN",
        description: "Ideal para bodas que se celebran en m├║ltiples locaciones o durante varios d├¡as. Particularmente adecuada para una cobertura extendida de la fiesta. Incluye una sesi├│n previa y otra posterior, que pueden utilizarse con el prop├│sito que ustedes deseen. Cada momento se captura para tener un recuerdo extendido de todos los aspectos de su celebraci├│n.",
      },
      {
        name: "Colecci├│n Diamante",
        features: [
          "12 horas de cobertura",
          "2 fot├│grafos",
          "1000+ fotograf├¡as",
          "Galer├¡a digital",
          "2 vide├│grafos",
          "Video de 45ÔÇô60 minutos",
          "Versi├│n 3ÔÇô5 minutos",
          "Versi├│n 1 minuto",
          "Creador de contenido",
          "Dron para tomas a├®reas",
          'Photobook 12x12" (75 p├íginas)',
          "Invitaci├│n digital",
          "Sesi├│n pre boda",
          "Sesi├│n post boda",
        ],
        price: "$89,000 MXN",
        description: "Dise├▒ada para celebrar en grande, con cobertura en m├║ltiples locaciones. Con sesiones antes y despu├®s de la boda. Cada detalle se captura desde m├║ltiples ├íngulos, permitiendo una visi├│n din├ímica y precisa. Recomendada para grandes celebraciones con m├ís de 300 invitados y para la cobertura dirigida a redes sociales.",
      },
    ],
    customNote: "Si su boda tiene caracter├¡sticas muy espec├¡ficas (bodas destino, celebraciones de varios d├¡as, eventos ├¡ntimos fuera de la ciudad), podemos ajustar cualquiera de estas colecciones o crear una propuesta a la medida. Escr├¡bannos y lo dise├▒amos juntos.",
    comparisonTitle: "Comparaci├│n de colecciones",
    featuresTitle: "Caracter├¡sticas",
    priceTitle: "Precio",
    addonsTitle: "Adicionales",
    checkAvailability: "[ Consultar disponibilidad ]",
    comparisonLabels: {
      coverage: "Horas de cobertura",
      photographers: "Fot├│grafos",
      photos: "Fotograf├¡as",
      videographers: "Vide├│grafos",
      videoDuration: "Video (duraci├│n)",
      shortVideo: "Video corto (3ÔÇô5 min)",
      oneMinuteVideo: "Video 1 minuto",
      photobook: "Photobook",
      preWedding: "Sesi├│n pre boda",
      postWedding: "Sesi├│n post boda",
      drone: "Dron para tomas a├®reas",
      contentCreator: "Creador de contenido",
      digitalInvitation: "Invitaci├│n digital",
    },
    whatsappText: "┬┐Listo para reservar tu fecha? Escr├¡benos por WhatsApp y conversemos sobre tu boda.",
    whatsappButton: "Contactar por WhatsApp",
    whatsappMessage: "┬íHola! Deseo m├ís informaci├│n sobre sus servicios de fotograf├¡a y video",
    addons: [
      {
        name: "Hora extra (fotograf├¡a y video)",
        price: "$8,500",
      },
      {
        name: "Dron para tomas a├®reas",
        price: "$6,500",
      },
      {
        name: 'Photobook 50 p├íginas (11x11")',
        price: "$5,500",
      },
      {
        name: "Caja para Photobook",
        price: "$1,500",
      },
      {
        name: "Camar├│grafo adicional",
        price: "$7,000",
      },
      {
        name: "Creador de contenido",
        price: "$7,000",
      },
      {
        name: "Invitaci├│n digital",
        price: "$5,000",
      },
    ],
  },
  contacto: {
    title: "Contacto",
    subtitle: "Cu├®ntenos sobre su boda",
    intro: "Queremos saber m├ís sobre ustedes. Todos los detalles nos ayudar├ín a plasmar mejor su d├¡a.",
    fields: {
      couple: "Nombre de la pareja",
      email: "Correo electr├│nico",
      phone: "Tel├®fono",
      date: "Fecha tentativa de la boda",
      venue: "Lugar / venue (si ya lo tienen)",
      guests: "N├║mero de invitados",
      source: "C├│mo nos conocieron",
      message: "Mensaje",
    },
    sourceOptions: [
      "Instagram",
      "Recomendaci├│n",
      "Planner",
      "B├║squeda en Google",
      "Otro",
    ],
    disclaimer: "Respondemos personalmente cada mensaje y procuramos hacerlo en menos de 24ÔÇô48 horas. Si no reciben respuesta, revisen su carpeta de spam o escr├¡bannos directamente a: hola@arrebolweddings.com",
    successMessage: "Gracias por su mensaje. Nos pondremos en contacto con ustedes pronto.",
    selectOption: "Seleccionar...",
    submitButton: "Enviar mensaje",
    whatsappText: "┬┐Prefieres WhatsApp? ┬íEs la forma m├ís r├ípida de ponernos en contacto contigo!",
    whatsappButton: "Contactar por WhatsApp",
    whatsappMessage: "┬íHola! Deseo m├ís informaci├│n sobre sus servicios de fotograf├¡a y video",
  },
  blog: {
    title: "NUESTRO BLOG",
    subtitle: "Reflexiones sobre bodas",
    description: "Reflexiones sobre bodas, amor y todo lo que hay en medio. Art├¡culos para ayudarte a planear, decidir y disfrutar tu camino al altar.",
    readMore: "Ver m├ís art├¡culos",
    relatedPosts: "Tambi├®n te puede interesar",
    navigation: {
      previous: "ÔåÉ Anterior",
      next: "Siguiente ÔåÆ",
    },
    preview: {
      subtitle: "NUESTRO BLOG",
      title: "Consejos, ideas e inspiraci├│n",
      description: "Reflexiones sobre bodas, amor y todo lo que hay en medio. Art├¡culos para ayudarte a planear, decidir y disfrutar tu camino al altar.",
      cta: "Ver todas las entradas",
    },
    page: {
      journal: "Journal",
      heroTitle: "Historias & Inspiraci├│n",
      heroDescription: "Un espacio dedicado a compartir bodas reales, consejos de planificaci├│n y la belleza detr├ís de cada detalle.",
      latestPosts: "├Ültimas Publicaciones",
      postsPage: "Publicaciones - P├ígina",
      articles: "art├¡culos",
      ctaTitle: "┬┐Planeando tu boda?",
      ctaDescription: "Escr├¡benos para revisar tu fecha, conocer tus planes y construir juntos el recuerdo de ese d├¡a.",
      ctaButton: "Contactar por WhatsApp",
      ctaMessage: "Hola! Vengo del blog y quisiera m├ís informaci├│n",
    },
  },
  footer: {
    tagline: "Recuerdos que se vuelven m├ís valiosos con el tiempo",
    email: "hola@arrebolweddings.com",
    instagram: "@arrebolweddings",
    copyright: "┬® 2025 Arrebol Weddings. Todos los derechos reservados.",
    note: "Porque las mejores historias merecen ser contadas con cuidado.",
  },
};

export const contentEn = {
  common: {
    menu: "MENU",
    close: "CLOSE",
    viewMore: "View more",
    loading: "Loading...",
    goToContact: "Go to contact",
    navigation: {
      home: "HOME",
      gallery: "GALLERY",
      process: "THE PROCESS",
      collections: "COLLECTIONS",
      blog: "BLOG",
      contact: "CONTACT",
    },
    cookieAlert: {
      message: "We use cookies to ensure that you have the best experience on our website.",
      button: "Accept",
    },
    privacyPolicy: {
      title: "Privacy Policy",
      content: "Privacy policy content...",
    },
  },
  home: {
    hero: {
      taglinePart1: "MEMORIES",
      taglinePart2: "that last for",
      taglinePart3: "GENERATIONS",
      title: "We capture the kind of memories that become more valuable with time",
      subtitle: "At Arrebol Weddings, we tell love stories that have already traveled a path. We don't see the wedding as a beginning, but as the consolidation of everything you have lived together.",
      cta1: "View our gallery",
      cta2: "Schedule a call",
    },
    about: {
      title: "Memories for a lifetime",
      text: "Your wedding is much more than a commitment; it is the celebration of a love story that is about to begin a new chapter. In every glance, every smile, and every tear of happiness, there is a moment that deserves to be kept forever.\n\nWe are passionate about telling stories through our cameras and being part of one of the most important days of your lives. Every detail, from the preparations to the last song of the night, reflects the essence of your love.\n\nWe want that when you look back, every image transports you to those magical moments. For us, capturing your story is a way of honoring the beauty of that day, leaving an indelible mark that will last a lifetime.",
      quote: "We capture the kind of images that become more valuable with time",
    },
    philosophy: {
      line1: "We are moments that pass, images that bring nostalgia.",
      line2: "One day we will be a memory, and the photo and video will be the most faithful echo of what we were:",
      line3: "the simplest way to return to a moment that is no longer there.",
    },
    values: [
      {
        title: "Memories age beautifully",
        description: "We believe in a style that withstands passing trends so that your photos and videos continue to look current in many years.",
      },
      {
        title: "Moments that flow",
        description: "We don't force uncomfortable poses. We seek for everything to happen naturally and for the emotion to be genuine.",
      },
      {
        title: "Close accompaniment",
        description: "From the first call to the final delivery, we are present to answer questions, calm nerves, and help you enjoy the process.",
      },
    ],
    stories: {
      title: "Some of the stories we have had the joy of telling",
      subtitle: "Every wedding is different, but in all of them we seek the same thing: that you recognize yourselves when you see your memories.",
      viewStory: "View story",
      featured: [
        { couple: "Mar├¡a & Carlos", venue: "Hacienda San Antonio, Quer├®taro" },
        { couple: "Andrea & Roberto", venue: "Casa de Piedra, San Miguel de Allende" },
        { couple: "Sof├¡a & Daniel", venue: "Vi├▒edos La Redonda, Guanajuato" },
        { couple: "Valeria & Alejandro", venue: "Hotel Matilda, San Miguel de Allende" },
        { couple: "Fernanda & Luis", venue: "Rancho Las Sabinas, Guanajuato" },
        { couple: "Paola & Miguel", venue: "Hacienda Sep├║lveda, Quer├®taro" },
      ],
    },
    process: {
      title: "How we work",
      steps: [
        {
          title: "First conversation",
          description: "We get to know each other, you tell us your story, and we answer all your questions.",
        },
        {
          title: "Planning and accompaniment",
          description: "We review the wedding timeline, define priorities, and coordinate with your planner or venue.",
        },
        {
          title: "The wedding day",
          description: "We arrive early, work discreetly, and always look for the best light and the most significant moments.",
        },
      ],
    },
    testimonials: {
      title: "What couples who have trusted us say",
      items: [
        {
          quote: "We have no words to thank you for the joy it was to work with you. From the beginning you were accessible, kind and super professional. Having the video and photos with you guaranteed that our memories remain forever, just as we imagined them. Thanks for all the time to plan this, for the session and the save the date videos that everyone loved.",
          author: "Cris",
        },
        {
          quote: "From the day we contacted you we had impeccable attention, totally professional and more than recommended!",
          author: "Karen",
        },
        {
          quote: "Anthony and Brenda are very good people and photographers. They made our event special. At all times they were extremely kind and flexible. Highly recommended.",
          author: "Andrea",
        },
        {
          quote: "Anthony and Brenda captured our wedding in an incredible and very professional way, plus they are wonderful beings. Much talent!",
          author: "Carolina",
        },
        {
          quote: "Honestly, I was surprised by so much professionalism, attention and flexibility. We were more than satisfied with the photographs and video!! WITHOUT A DOUBT I highly recommend Brenda and Anthony!!",
          author: "Yetzy",
        },
        {
          quote: "Anthony captured our wedding and exceeded all our expectations. From all the photos to the video, Arrebol outdid itself. They are professional, kind and incredibly talented. I highly recommend using Arrebol for your wedding/engagement photos!",
          author: "Valeria",
        },
        {
          quote: "You will never regret it! Punctual, cheerful, it is very easy to pose naturally, excellent quality photos, attentive! We are very happy with their work and having hired them, without a doubt I will do it for another event I have.",
          author: "Paula",
        },
        {
          quote: "The Arrebol team was extremely clear and professional at all times. They were attentive all the time, made us feel very good during the session and the photos turned out beautiful, just like the album. We are looking to see each other again for our anniversary!",
          author: "Guadalupe",
        },
        {
          quote: "Anthony and Brenda are very good people and photographers. They made our event special. At all times they were extremely kind and flexible.",
          author: "Andrick",
        },
        {
          quote: "My wedding was in Temixco, I am from another state and they were always attentive and accessible. Incredible photos and video, it looks like a movie. The quality of our photos has no comparison, great work from your team. Thanks Arrebol.",
          author: "Brenda",
        },
        {
          quote: "Working with Arrebol was an absolute dream! The photos are stunning and tell our story perfectly.",
          author: "Jonathan",
        },
        {
          quote: "From the engagement shoot to the wedding day, they made us feel so comfortable and captured every special moment beautifully.",
          author: "Tory",
        },
      ],
    },
    finalCta: {
      title: "Would you like us to tell your story?",
      subtitle: "Write to us to check your date, learn about your plans, and build together the memory of that day.",
      button: "Go to contact",
      whatsappIntro: "Or write to us directly on WhatsApp:",
      whatsappButton: "Contact on WhatsApp",
      whatsappMessage: "Hello! I would like more information about your photography and video services",
    },
  },
  galeria: {
    title: "Gallery",
    subtitle: "A sample of the stories we have told",
    intro: "Here you can see a bit of our work in different venues, wedding styles, and times. Every couple has their own rhythm, their own light, and their own way of loving. Our job is to find it.",
    viewFullGallery: "View full gallery",
    loading: "Loading gallery...",
    whatsappText: "The fastest way to contact us is via WhatsApp. Don't hesitate to write to us!",
    whatsappButton: "Contact on WhatsApp",
    whatsappMessage: "Hello! I would like more information about your photography and video services",
    filters: {
      all: "ALL",
      photos: "PHOTOS",
      clips: "CLIPS",
    },
    picTime: {
      text: "Explore our complete wedding galleries on our photo delivery platform, where you'll find hundreds of images from each celebration.",
      button: "View full galleries on Pic-Time",
    },
    vidflow: {
      text: "See how we deliver videos to our couples. This gallery shows a complete example with all the final versions.",
      button: "View full gallery on Vidflow",
    },
    combined: {
      text: "Explore our complete wedding galleries. Each couple receives their photo gallery on Pic-Time and their video delivery on Vidflow.",
      picTimeButton: "View photos on Pic-Time",
      vidflowButton: "View videos on Vidflow",
    },
    images: contentEs.galeria.images,
  },
  proceso: {
    title: "The process",
    subtitle: "From the first call to the final delivery",
    intro: "We like everything to be clear from the start. These are the stages we will go through together and what you can expect in each one.",
    steps: [
      {
        title: "First call",
        description: "We talk in detail about your wedding, your story, and the essence of what you imagine for that day. You tell us what you like, what you prefer to avoid, and what moments you consider most important. We also check date availability and answer all your questions about packages, coverage, times, and our way of working. It is a close and simple conversation, designed to start understanding your style and what you are looking for in your memories.",
      },
      {
        title: "Contract signing and date reservation",
        description: "Once you decide to move forward, we formalize the reservation with a clear, simple contract with no small print. To secure your date, a 30% advance payment is made, with which it is officially reserved in our calendar. From that moment, you can relax: we keep track of times and keep you informed at every stage.",
      },
      {
        title: "Planning meeting",
        description: "A few weeks before the wedding, we review the detailed timeline together: schedules, venues, estimated weather, important people, key moments, and any surprises or special dynamics you are preparing. This step allows us to anticipate what will happen and ensure that every significant moment is recorded without stress or improvisation.",
      },
      {
        title: "The wedding day",
        description: "We arrive early and coordinate with your wedding planner, the venue, and the providers involved. We work discreetly, without interrupting or forcing situations. Our gaze is mainly documentary, but we also guide certain moments to ensure natural portraits, with good light and that really reflect who you are. You just have to live your day; we take care of the rest.",
      },
      {
        title: "Selection and editing",
        description: "After the wedding, we perform a careful curation in which we select the best images, those that tell the story with emotion and coherence. Each photograph is edited one by one following a timeless style. In parallel, we build the video narrative so that it flows and evokes the entire day, not just the main moments.",
      },
      {
        title: "Delivery",
        description: "We prepare an online gallery where you can view, download, and share your material. Depending on the package, you also receive a printed album or box with prints. Our goal is for the delivery experience to be as special as the wedding itself: clean, organized, and designed for you to enjoy your memories as many times as you want.",
      },
    ],
    whatsappText: "Ready to start? Contact us via WhatsApp to schedule a video call.",
    whatsappButton: "Contact on WhatsApp",
    whatsappMessage: "Hello! I would like more information about your photography and video services",
  },
  colecciones: {
    title: "Collections",
    subtitle: "Photography and video to tell your wedding from start to finish",
    intro: "Our collections are designed to adapt to different types of weddings: from intimate celebrations in a single location to large events in multiple venues and several days. All include photography and video, as well as a careful curation of every moment.",
    collections: [
      {
        name: "Collection One",
        features: [
          "8 hours of coverage",
          "1 photographer",
          "400ÔÇô500 photographs",
          "Digital gallery",
          "1 videographer",
          "20ÔÇô30 minute video",
          "1 minute version",
          '8.5x11" Photobook (50 pages)',
        ],
        price: "$49,000 MXN",
        description: "Ideal for intimate weddings in a single location, capturing preparations, ceremony, and reception. Designed to highlight the most special moments and personal connection of celebrations with up to 150 guests.",
      },
      {
        name: "Collection Two",
        features: [
          "10 hours of coverage",
          "1 photographer",
          "600ÔÇô700 photographs",
          "Digital gallery",
          "1 videographer",
          "30ÔÇô40 minute video",
          "3ÔÇô5 minute version",
          "1 minute version",
          '8.5x11" Photobook (50 pages)',
          "Pre-wedding session",
        ],
        price: "$59,000 MXN",
        description: "Designed for comprehensive coverage of weddings in one or multiple locations, capturing every detail of the day. From preparations to the most spectacular moments. Includes a previous session you can use for casual photos, civil ceremony, rehearsal dinner, or any other special moment.",
      },
      {
        name: "Collection Three",
        features: [
          "12 hours of coverage",
          "1 photographer",
          "800ÔÇô900 photographs",
          "Digital gallery",
          "1 videographer",
          "50ÔÇô60 minute video",
          "3ÔÇô5 minute version",
          "1 minute version",
          '11x11" Photobook (50 pages)',
          "Pre-wedding session",
          "Post-wedding session",
        ],
        price: "$69,000 MXN",
        description: "Ideal for weddings held in multiple locations or over several days. Particularly suitable for extended party coverage. Includes a previous and a subsequent session, which can be used for whatever purpose you wish. Every moment is captured to have an extended memory of all aspects of your celebration.",
      },
      {
        name: "Diamond Collection",
        features: [
          "12 hours of coverage",
          "2 photographers",
          "1000+ photographs",
          "Digital gallery",
          "2 videographers",
          "45ÔÇô60 minute video",
          "3ÔÇô5 minute version",
          "1 minute version",
          "Content creator",
          "Drone for aerial shots",
          '12x12" Photobook (75 pages)',
          "Digital invitation",
          "Pre-wedding session",
          "Post-wedding session",
        ],
        price: "$89,000 MXN",
        description: "Designed to celebrate big, with coverage in multiple locations. With sessions before and after the wedding. Every detail is captured from multiple angles, allowing for a dynamic and precise vision. Recommended for large celebrations with more than 300 guests and for coverage aimed at social media.",
      },
    ],
    customNote: "If your wedding has very specific characteristics (destination weddings, multi-day celebrations, intimate events out of town), we can adjust any of these collections or create a custom proposal. Write to us and we'll design it together.",
    comparisonTitle: "Collection Comparison",
    featuresTitle: "Features",
    priceTitle: "Price",
    addonsTitle: "Add-ons",
    checkAvailability: "[ Check availability ]",
    comparisonLabels: {
      coverage: "Coverage hours",
      photographers: "Photographers",
      photos: "Photographs",
      videographers: "Videographers",
      videoDuration: "Video (duration)",
      shortVideo: "Short video (3ÔÇô5 min)",
      oneMinuteVideo: "1 minute video",
      photobook: "Photobook",
      preWedding: "Pre-wedding session",
      postWedding: "Post-wedding session",
      drone: "Drone for aerial shots",
      contentCreator: "Content creator",
      digitalInvitation: "Digital invitation",
    },
    whatsappText: "Ready to book your date? Write to us on WhatsApp and let's talk about your wedding.",
    whatsappButton: "Contact on WhatsApp",
    whatsappMessage: "Hello! I would like more information about your photography and video services",
    addons: [
      {
        name: "Extra hour (photography and video)",
        price: "$8,500",
      },
      {
        name: "Drone for aerial shots",
        price: "$6,500",
      },
      {
        name: '50-page Photobook (11x11")',
        price: "$5,500",
      },
      {
        name: "Photobook Box",
        price: "$1,500",
      },
      {
        name: "Additional videographer",
        price: "$7,000",
      },
      {
        name: "Content creator",
        price: "$7,000",
      },
      {
        name: "Digital invitation",
        price: "$5,000",
      },
    ],
  },
  contacto: {
    title: "Contact",
    subtitle: "Tell us about your wedding",
    intro: "We want to know more about you. All the details will help us better capture your day.",
    fields: {
      couple: "Couple's name",
      email: "Email",
      phone: "Phone",
      date: "Tentative wedding date",
      venue: "Venue (if you have one)",
      guests: "Approximate number of guests",
      source: "How did you hear about us",
      message: "Message",
    },
    sourceOptions: [
      "Instagram",
      "Recommendation",
      "Planner",
      "Google Search",
      "Other",
    ],
    disclaimer: "We personally answer every message and try to do so in less than 24ÔÇô48 hours. If you don't receive a response, check your spam folder or write to us directly at: hola@arrebolweddings.com",
    successMessage: "Thank you for your message. We will contact you soon.",
    selectOption: "Select...",
    submitButton: "Send message",
    whatsappText: "Do you prefer WhatsApp? It's the fastest way to get in touch with you!",
    whatsappButton: "Contact on WhatsApp",
    whatsappMessage: "Hello! I would like more information about your photography and video services",
  },
  blog: {
    title: "OUR BLOG",
    subtitle: "Reflections on weddings",
    description: "Reflections on weddings, love, and everything in between. Articles to help you plan, decide, and enjoy your journey to the altar.",
    readMore: "See more articles",
    relatedPosts: "You may also like",
    navigation: {
      previous: "ÔåÉ Previous",
      next: "Next ÔåÆ",
    },
    preview: {
      subtitle: "OUR BLOG",
      title: "Tips, ideas & inspiration",
      description: "Reflections on weddings, love, and everything in between. Articles to help you plan, decide, and enjoy your journey to the altar.",
      cta: "View all posts",
    },
    page: {
      journal: "Journal",
      heroTitle: "Stories & Inspiration",
      heroDescription: "A space dedicated to sharing real weddings, planning tips, and the beauty behind every detail.",
      latestPosts: "Latest Posts",
      postsPage: "Posts - Page",
      articles: "articles",
      ctaTitle: "Planning your wedding?",
      ctaDescription: "Write to us to check your date, learn about your plans, and build together the memory of that day.",
      ctaButton: "Contact on WhatsApp",
      ctaMessage: "Hello! I come from the blog and would like more information",
    },
  },
  footer: {
    tagline: "Memories that become more valuable with time",
    email: "hola@arrebolweddings.com",
    instagram: "@arrebolweddings",
    copyright: "┬® 2025 Arrebol Weddings. All rights reserved.",
    note: "Because the best stories deserve to be told with care.",
  },
};

export const content = contentEs;

