// Landing page content - Spanish and English translations

export const landingContentEs = {
  hero: {
    badge: "Fotografía & Video de Bodas",
    headline: "Tus recuerdos hoy.\nEl tesoro de tu familia mañana.",
    subheadline:
      "Fotografía y video de bodas que capturan emociones reales, con un acompañamiento cercano y humano.",
    ctaPrimary: "Consultar disponibilidad",
    ctaSecondary: "Ver nuestro trabajo",
    trustBadge: "Respondemos en menos de 24 horas",
    whatsappMessage: "Hola! Vi su landing page y me gustaría consultar disponibilidad para mi boda.",
  },
  about: {
    subtitle: "Quiénes somos",
    title: "Recuerdos para toda la vida",
    paragraphs: [
      "Su boda es la celebración de una historia de amor que está a punto de comenzar un nuevo capítulo. En cada mirada, cada sonrisa y cada lágrima de felicidad, hay un momento que merece ser guardado para siempre.",
      "Nos apasiona contar historias a través de nuestras cámaras. Cada detalle, desde los preparativos hasta la última canción de la noche, refleja la esencia de su amor.",
    ],
    quote: "Capturamos el tipo de imágenes que se vuelven más valiosos con el tiempo",
    signature: "— Brenda & Anthony",
    values: [
      {
        title: "Los recuerdos envejecen hermoso",
        description: "Creemos en un estilo que resista modas pasajeras para que sus fotos y videos se sigan viendo actuales dentro de muchos años.",
      },
      {
        title: "Momentos que fluyen",
        description: "No forzamos poses incómodas. Buscamos que todo suceda con naturalidad y que la emoción sea genuina.",
      },
      {
        title: "Acompañamiento cercano",
        description: "Desde la primera llamada hasta la entrega final, estamos presentes para responder dudas, calmar nervios y ayudarles a disfrutar el proceso.",
      },
    ],
  },
  gallery: {
    loading: "Cargando galería...",
  },
  stories: {
    subtitle: "Portafolio",
    title: "Historias reales, emociones reales",
    description: "Cada pareja tiene su propia forma de amarse. Nosotros la encontramos y la contamos.",
    viewStory: "Ver historia completa",
    items: [
      {
        couple: "Karyme & Brian",
        location: "Hacienda San Antonio el Puente",
        description: "Una celebración llena de tradición y familia en una hermosa hacienda. Cada imagen cuenta la historia de dos familias que se unieron en un día inolvidable.",
        highlight: "Hacienda tradicional",
      },
      {
        couple: "Carla & Diego",
        location: "Jardín Lomasol",
        description: "Una boda íntima llena de risas y momentos genuinos. Su prioridad era disfrutar con sus seres queridos, sin poses rígidas, solo momentos reales que ahora atesoran para siempre.",
        highlight: "Boda íntima",
      },
      {
        couple: "Sofía & Óscar",
        location: "Jardín Huayacán",
        description: "Un amor tranquilo pero profundo. Capturamos la complicidad en sus miradas y la ternura de cada gesto pequeño que define su relación.",
        highlight: "Estilo documental",
      },
    ],
  },
  uniqueValue: {
    subtitle: "Por qué elegirnos",
    title: "Lo que nos hace diferentes",
    values: [
      {
        title: "Acompañamiento cercano",
        description: "Desde la primera llamada hasta la entrega, estaremos contigo. No somos solo proveedores, somos parte de tu equipo.",
      },
      {
        title: "Estilo emocional y auténtico",
        description: "No buscamos poses perfectas, buscamos momentos reales. Capturamos la esencia de tu relación tal como es.",
      },
      {
        title: "Entrega de calidad premium",
        description: "Fotos y video editados con dedicación, en tiempos razonables, con una narrativa que cuenta tu historia única.",
      },
    ],
  },
  process: {
    subtitle: "El proceso",
    title: "Cómo trabajamos juntos",
    description: "Desde la primera llamada hasta la entrega, cada paso está diseñado para que disfruten el proceso tanto como el resultado.",
    readyToStart: "¿Listos para comenzar?",
    scheduleCall: "Agendar llamada",
    whatsappMessage: "Hola! Vi su landing page y me gustaría agendar una llamada.",
    steps: [
      {
        number: "01",
        title: "Conexión",
        description: "Agendamos una videollamada para conocer su historia, su visión y lo que les gustaría recordar de su boda. Sin presión, solo conversación genuina.",
      },
      {
        number: "02",
        title: "Cobertura",
        description: "El día de la boda trabajamos de forma discreta, atentos a lo que sucede, sin interrumpir el flujo natural del evento. Ustedes disfrutan, nosotros observamos.",
      },
      {
        number: "03",
        title: "Entrega",
        description: "Recibirán fotos y video editados con una narrativa personalizada, listos para revivir y compartir durante generaciones.",
      },
    ],
  },
  testimonials: {
    subtitle: "Testimonios",
    title: "Lo que dicen nuestras parejas",
    badge: "Más de 200 parejas han confiado en nosotros",
    viewTestimonial: "Ver testimonio",
    items: [
      {
        couple: "Ana Cristina & Ettiene",
        quote: "No tenemos palabras para agradecer la gozada que fue trabajar con ustedes. Desde un inicio se mostraron accesibles, amables y super profesionales. Tener el video y las fotos con ustedes garantizó que nuestros recuerdos queden para siempre, justo como los imaginábamos.",
        location: "Hacienda Santa Cruz Vista Alegre",
        highlight: "Justo como lo imaginábamos",
      },
      {
        couple: "Paula & Orlando",
        quote: "No se van a arrepentir nunca! Puntuales, alegres, te es muy fácil posar naturalmente, las fotos con excelente calidad, atentos! Estamos muy felices con su trabajo y de haberlos contratado, sin duda lo haré para otro evento que tenga.",
        location: "Jardín Santa Bárbara",
        highlight: "No se van a arrepentir",
      },
      {
        couple: "Tory & Jonathan",
        quote: "Anthony y Brenda fueron increíbles y nos proporcionaron un producto que nos ayudará a recordar cada momento de nuestro día especial para toda la vida. Las fotos y el video salieron absolutamente asombrosos. No podríamos haber pedido un mejor equipo.",
        location: "Casanueva by Las Mañanitas",
        highlight: "Absolutamente asombrosos",
      },
      {
        couple: "Ana Pau & Robert",
        quote: "Anthony y Bren son lo máximo! Ya los recomendé con todas mis amigas que se van a casar. Gracias por su excelente trabajo y dedicación. Son los más fregones, los quiero y admiro!",
        location: "Casanueva by Las Mañanitas",
        highlight: "Los más fregones",
      },
      {
        couple: "Nuria & Alejandro",
        quote: "Amamos el teaser, la canción, las tomas que eligieron. Brutales las fotos Anthony y Brenda, gran gran trabajo. De verdad estamos felices con el resultado.",
        location: "Hacienda Acamilpa",
        highlight: "Espectacular",
      },
      {
        couple: "Carla & Diego",
        quote: "Desde la primera llamada supimos que eran los indicados. Su forma de trabajar es tan natural que olvidamos que había cámaras. Las fotos capturan exactamente lo que sentimos ese día.",
        location: "Jardín Lomasol",
        highlight: "Superaron nuestras expectativas",
      },
    ],
  },
  packages: {
    subtitle: "Nuestras Colecciones",
    title: "Fotografía y video para contar su boda",
    intro: "Nuestras colecciones están pensadas para adaptarse a distintos tipos de boda: desde celebraciones íntimas hasta grandes eventos en múltiples sedes. Todas incluyen fotografía y video.",
    hideComparison: "Ocultar comparación",
    showComparison: "Ver comparación detallada",
    comparisonTitle: "Comparación de colecciones",
    features: "Características",
    price: "Precio",
    customNote: "Si su boda tiene características muy específicas (bodas destino, celebraciones de varios días), podemos ajustar cualquiera de estas colecciones o crear una propuesta a la medida.",
    requestQuote: "Solicitar cotización personalizada",
    whatsappMessage: "Hola! Vi su landing page y me gustaría conocer más sobre sus colecciones.",
    collections: [
      {
        name: "Colección Uno",
        description: "Ideal para bodas íntimas en una sola ubicación, capturando los preparativos, la ceremonia y la recepción. Diseñada para celebraciones con hasta 150 invitados.",
        features: [
          "8 horas de cobertura",
          "1 fotógrafo",
          "400–500 fotografías",
          "Galería digital",
          "1 videógrafo",
          "Video de 20–30 minutos",
          "Versión 1 minuto",
          'Photobook 8.5x11" (50 páginas)',
        ],
        price: "$49,000 MXN",
      },
      {
        name: "Colección Dos",
        description: "Cobertura integral en una o varias locaciones. Incluye una sesión previa que pueden usar para fotos casuales, el civil o rehearsal dinner.",
        features: [
          "10 horas de cobertura",
          "1 fotógrafo",
          "600–700 fotografías",
          "Galería digital",
          "1 videógrafo",
          "Video de 30–40 minutos",
          "Versión 3–5 minutos",
          "Versión 1 minuto",
          'Photobook 8.5x11" (50 páginas)',
          "Sesión pre boda",
        ],
        price: "$59,000 MXN",
      },
      {
        name: "Colección Tres",
        description: "Para bodas en múltiples locaciones o varios días. Incluye sesión previa y posterior para tener un recuerdo extendido de su celebración.",
        features: [
          "12 horas de cobertura",
          "1 fotógrafo",
          "800–900 fotografías",
          "Galería digital",
          "1 videógrafo",
          "Video de 50–60 minutos",
          "Versión 3–5 minutos",
          "Versión 1 minuto",
          'Photobook 11x11" (50 páginas)',
          "Sesión pre boda",
          "Sesión post boda",
        ],
        price: "$69,000 MXN",
      },
      {
        name: "Colección Diamante",
        description: "Diseñada para celebrar en grande. Con cobertura desde múltiples ángulos. Recomendada para +300 invitados y cobertura dirigida a redes sociales.",
        features: [
          "12 horas de cobertura",
          "2 fotógrafos",
          "1000+ fotografías",
          "Galería digital",
          "2 videógrafos",
          "Video de 45–60 minutos",
          "Versión 3–5 minutos",
          "Versión 1 minuto",
          "Creador de contenido",
          "Dron para tomas aéreas",
          'Photobook 12x12" (75 páginas)',
          "Invitación digital",
          "Sesión pre boda",
          "Sesión post boda",
        ],
        price: "$89,000 MXN",
      },
    ],
    comparison: {
      rows: [
        { label: "Horas de cobertura", values: ["8", "10", "12", "12"] },
        { label: "Fotógrafos", values: ["1", "1", "1", "2"] },
        { label: "Fotografías", values: ["400–500", "600–700", "800–900", "1000+"] },
        { label: "Videógrafos", values: ["1", "1", "1", "2"] },
        { label: "Video (duración)", values: ["20–30 min", "30–40 min", "50–60 min", "45–60 min"] },
        { label: "Video corto (3–5 min)", values: ["—", "✓", "✓", "✓"] },
        { label: "Video 1 minuto", values: ["✓", "✓", "✓", "✓"] },
        { label: "Photobook", values: ['8.5x11"', '8.5x11"', '11x11"', '12x12"'] },
        { label: "Sesión pre boda", values: ["—", "✓", "✓", "✓"] },
        { label: "Sesión post boda", values: ["—", "—", "✓", "✓"] },
        { label: "Dron", values: ["—", "—", "—", "✓"] },
        { label: "Creador de contenido", values: ["—", "—", "—", "✓"] },
        { label: "Invitación digital", values: ["—", "—", "—", "✓"] },
      ],
    },
  },
  whyInvest: {
    subtitle: "Una reflexión",
    title: "El día termina, los recuerdos quedan",
    paragraphs: [
      "La decoración se desmonta, el pastel se acaba, los invitados se van a casa. Pero las fotos y el video permanecen. Son lo único que queda del día más importante de sus vidas.",
      "Años después, cuando quieran recordar cómo se miraban ese día, cómo bailó su mamá, qué dijo su papá en el brindis, o cómo se veía su abuela sonriendo... solo tendrán las fotos y el video para volver a ese momento.",
      "Invertir en fotografía y video de calidad no es un gasto más en la lista. Es asegurar que esos momentos irrepetibles estén capturados con el cuidado que merecen, por profesionales que entienden lo que está en juego.",
    ],
    highlight: "Las flores se marchitan, el vestido se guarda, pero los recuerdos bien capturados se vuelven más valiosos con cada año que pasa.",
  },
  contact: {
    subtitle: "Comencemos",
    title: "Comencemos a contar su historia",
    description: "Cuéntennos sobre su boda y veamos si somos el equipo ideal para documentarla. Sin compromiso, solo una conversación para conocernos.",
    trustBadge: "Respondemos habitualmente en menos de 24 horas",
    sourceOptions: [
      "Instagram",
      "Google",
      "Recomendación de amigo/familiar",
      "Evento de bodas",
      "Otro",
    ],
    formLabels: {
      couple: "Nombres de la pareja *",
      email: "Correo electrónico *",
      phone: "Teléfono",
      date: "Fecha de la boda",
      venue: "Venue o ciudad",
      guests: "Número aproximado de invitados",
      source: "¿Cómo nos encontraron?",
      message: "Cuéntanos sobre ustedes y su boda *",
      submit: "Enviar mensaje",
    },
    successMessage: "¡Gracias por escribirnos! Pronto nos pondremos en contacto contigo.",
    errorMessage: "Hubo un error al enviar el mensaje. Por favor intenta de nuevo.",
    whatsappText: "¿Prefieren contactarnos directamente?",
    whatsappButton: "Escríbenos por WhatsApp",
    whatsappMessage: "Hola! Vi su landing page y me interesa conocer más sobre sus servicios",
  },
};

export const landingContentEn = {
  hero: {
    badge: "Wedding Photography & Video",
    headline: "Your memories today.\nYour family's treasure tomorrow.",
    subheadline:
      "Wedding photography and video that captures real emotions, with close and personal support.",
    ctaPrimary: "Check availability",
    ctaSecondary: "See our work",
    trustBadge: "We respond within 24 hours",
    whatsappMessage: "Hi! I saw your landing page and would like to check availability for my wedding.",
  },
  about: {
    subtitle: "Who we are",
    title: "Memories for a lifetime",
    paragraphs: [
      "Your wedding is the celebration of a love story about to begin a new chapter. In every glance, every smile, and every happy tear, there's a moment that deserves to be kept forever.",
      "We're passionate about telling stories through our cameras. Every detail, from the preparations to the last song of the night, reflects the essence of your love.",
    ],
    quote: "We capture the kind of images that become more valuable over time",
    signature: "— Brenda & Anthony",
    values: [
      {
        title: "Memories age beautifully",
        description: "We believe in a style that withstands passing trends so your photos and videos still look timeless many years from now.",
      },
      {
        title: "Moments that flow",
        description: "We don't force awkward poses. We want everything to happen naturally and emotions to be genuine.",
      },
      {
        title: "Close support",
        description: "From the first call to the final delivery, we're here to answer questions, calm nerves, and help you enjoy the process.",
      },
    ],
  },
  gallery: {
    loading: "Loading gallery...",
  },
  stories: {
    subtitle: "Portfolio",
    title: "Real stories, real emotions",
    description: "Every couple has their own way of loving. We find it and tell it.",
    viewStory: "See full story",
    items: [
      {
        couple: "Karyme & Brian",
        location: "Hacienda San Antonio el Puente",
        description: "A celebration full of tradition and family in a beautiful hacienda. Each image tells the story of two families that came together on an unforgettable day.",
        highlight: "Traditional hacienda",
      },
      {
        couple: "Carla & Diego",
        location: "Jardín Lomasol",
        description: "An intimate wedding full of laughter and genuine moments. Their priority was enjoying with loved ones, no stiff poses, just real moments they now treasure forever.",
        highlight: "Intimate wedding",
      },
      {
        couple: "Sofía & Óscar",
        location: "Jardín Huayacán",
        description: "A quiet but deep love. We captured the complicity in their glances and the tenderness of every small gesture that defines their relationship.",
        highlight: "Documentary style",
      },
    ],
  },
  uniqueValue: {
    subtitle: "Why choose us",
    title: "What makes us different",
    values: [
      {
        title: "Close support",
        description: "From the first call to delivery, we'll be with you. We're not just vendors, we're part of your team.",
      },
      {
        title: "Emotional and authentic style",
        description: "We don't look for perfect poses, we look for real moments. We capture the essence of your relationship as it is.",
      },
      {
        title: "Premium quality delivery",
        description: "Photos and video edited with dedication, in reasonable time, with a narrative that tells your unique story.",
      },
    ],
  },
  process: {
    subtitle: "The process",
    title: "How we work together",
    description: "From the first call to delivery, every step is designed for you to enjoy the process as much as the result.",
    readyToStart: "Ready to start?",
    scheduleCall: "Schedule a call",
    whatsappMessage: "Hi! I saw your landing page and would like to schedule a call.",
    steps: [
      {
        number: "01",
        title: "Connection",
        description: "We schedule a video call to learn about your story, your vision, and what you'd like to remember from your wedding. No pressure, just genuine conversation.",
      },
      {
        number: "02",
        title: "Coverage",
        description: "On the wedding day we work discreetly, attentive to what's happening, without interrupting the natural flow of the event. You enjoy, we observe.",
      },
      {
        number: "03",
        title: "Delivery",
        description: "You'll receive photos and video edited with a personalized narrative, ready to relive and share for generations.",
      },
    ],
  },
  testimonials: {
    subtitle: "Testimonials",
    title: "What our couples say",
    badge: "Over 200 couples have trusted us",
    viewTestimonial: "View testimonial",
    items: [
      {
        couple: "Ana Cristina & Ettiene",
        quote: "We have no words to thank you for how wonderful it was working with you. From the start you were accessible, kind and super professional. Having the video and photos with you guaranteed that our memories will last forever, just as we imagined.",
        location: "Hacienda Santa Cruz Vista Alegre",
        highlight: "Just as we imagined",
      },
      {
        couple: "Paula & Orlando",
        quote: "You won't ever regret it! Punctual, cheerful, it's so easy to pose naturally, excellent photo quality, attentive! We're very happy with your work and hiring you, I'll definitely do it again for any other event.",
        location: "Jardín Santa Bárbara",
        highlight: "You won't regret it",
      },
      {
        couple: "Tory & Jonathan",
        quote: "Anthony and Brenda were amazing and gave us a product that will help us remember every moment of our special day for life. The photos and video came out absolutely stunning. We couldn't have asked for a better team.",
        location: "Casanueva by Las Mañanitas",
        highlight: "Absolutely stunning",
      },
      {
        couple: "Ana Pau & Robert",
        quote: "Anthony and Bren are the best! I've already recommended them to all my friends getting married. Thank you for your excellent work and dedication. You're the coolest, I love and admire you!",
        location: "Casanueva by Las Mañanitas",
        highlight: "The best",
      },
      {
        couple: "Nuria & Alejandro",
        quote: "We loved the teaser, the song, the shots you chose. Amazing photos Anthony and Brenda, great great work. We're truly happy with the result.",
        location: "Hacienda Acamilpa",
        highlight: "Spectacular",
      },
      {
        couple: "Carla & Diego",
        quote: "From the first call we knew you were the right choice. Your way of working is so natural that we forgot there were cameras. The photos capture exactly what we felt that day.",
        location: "Jardín Lomasol",
        highlight: "Exceeded our expectations",
      },
    ],
  },
  packages: {
    subtitle: "Our Collections",
    title: "Photography and video to tell your wedding",
    intro: "Our collections are designed to adapt to different types of weddings: from intimate celebrations to large events in multiple venues. All include photography and video.",
    hideComparison: "Hide comparison",
    showComparison: "See detailed comparison",
    comparisonTitle: "Collections comparison",
    features: "Features",
    price: "Price",
    customNote: "If your wedding has very specific characteristics (destination weddings, multi-day celebrations), we can adjust any of these collections or create a custom proposal.",
    requestQuote: "Request custom quote",
    whatsappMessage: "Hi! I saw your landing page and would like to know more about your collections.",
    collections: [
      {
        name: "Collection One",
        description: "Ideal for intimate weddings in a single location, capturing preparations, ceremony and reception. Designed for celebrations with up to 150 guests.",
        features: [
          "8 hours of coverage",
          "1 photographer",
          "400–500 photographs",
          "Digital gallery",
          "1 videographer",
          "20–30 minute video",
          "1 minute version",
          '8.5x11" Photobook (50 pages)',
        ],
        price: "$49,000 MXN",
      },
      {
        name: "Collection Two",
        description: "Full coverage at one or multiple locations. Includes a pre-session you can use for casual photos, civil ceremony or rehearsal dinner.",
        features: [
          "10 hours of coverage",
          "1 photographer",
          "600–700 photographs",
          "Digital gallery",
          "1 videographer",
          "30–40 minute video",
          "3–5 minute version",
          "1 minute version",
          '8.5x11" Photobook (50 pages)',
          "Pre-wedding session",
        ],
        price: "$59,000 MXN",
      },
      {
        name: "Collection Three",
        description: "For weddings in multiple locations or several days. Includes pre and post session to have an extended memory of your celebration.",
        features: [
          "12 hours of coverage",
          "1 photographer",
          "800–900 photographs",
          "Digital gallery",
          "1 videographer",
          "50–60 minute video",
          "3–5 minute version",
          "1 minute version",
          '11x11" Photobook (50 pages)',
          "Pre-wedding session",
          "Post-wedding session",
        ],
        price: "$69,000 MXN",
      },
      {
        name: "Diamond Collection",
        description: "Designed to celebrate big. With coverage from multiple angles. Recommended for 300+ guests and social media-focused coverage.",
        features: [
          "12 hours of coverage",
          "2 photographers",
          "1000+ photographs",
          "Digital gallery",
          "2 videographers",
          "45–60 minute video",
          "3–5 minute version",
          "1 minute version",
          "Content creator",
          "Drone for aerial shots",
          '12x12" Photobook (75 pages)',
          "Digital invitation",
          "Pre-wedding session",
          "Post-wedding session",
        ],
        price: "$89,000 MXN",
      },
    ],
    comparison: {
      rows: [
        { label: "Hours of coverage", values: ["8", "10", "12", "12"] },
        { label: "Photographers", values: ["1", "1", "1", "2"] },
        { label: "Photographs", values: ["400–500", "600–700", "800–900", "1000+"] },
        { label: "Videographers", values: ["1", "1", "1", "2"] },
        { label: "Video (duration)", values: ["20–30 min", "30–40 min", "50–60 min", "45–60 min"] },
        { label: "Short video (3–5 min)", values: ["—", "✓", "✓", "✓"] },
        { label: "1 minute video", values: ["✓", "✓", "✓", "✓"] },
        { label: "Photobook", values: ['8.5x11"', '8.5x11"', '11x11"', '12x12"'] },
        { label: "Pre-wedding session", values: ["—", "✓", "✓", "✓"] },
        { label: "Post-wedding session", values: ["—", "—", "✓", "✓"] },
        { label: "Drone", values: ["—", "—", "—", "✓"] },
        { label: "Content creator", values: ["—", "—", "—", "✓"] },
        { label: "Digital invitation", values: ["—", "—", "—", "✓"] },
      ],
    },
  },
  whyInvest: {
    subtitle: "A reflection",
    title: "The day ends, the memories remain",
    paragraphs: [
      "The decorations come down, the cake is finished, the guests go home. But the photos and video remain. They're the only thing left from the most important day of your lives.",
      "Years later, when you want to remember how you looked at each other that day, how your mom danced, what your dad said in the toast, or how your grandmother smiled... you'll only have the photos and video to return to that moment.",
      "Investing in quality photography and video isn't just another expense on the list. It's ensuring those unrepeatable moments are captured with the care they deserve, by professionals who understand what's at stake.",
    ],
    highlight: "Flowers wilt, the dress gets stored away, but well-captured memories become more valuable with each passing year.",
  },
  contact: {
    subtitle: "Let's begin",
    title: "Let's start telling your story",
    description: "Tell us about your wedding and let's see if we're the ideal team to document it. No commitment, just a conversation to get to know each other.",
    trustBadge: "We usually respond within 24 hours",
    sourceOptions: [
      "Instagram",
      "Google",
      "Friend/family recommendation",
      "Wedding event",
      "Other",
    ],
    formLabels: {
      couple: "Couple's names *",
      email: "Email *",
      phone: "Phone",
      date: "Wedding date",
      venue: "Venue or city",
      guests: "Approximate number of guests",
      source: "How did you find us?",
      message: "Tell us about yourselves and your wedding *",
      submit: "Send message",
    },
    successMessage: "Thank you for writing! We'll get in touch with you soon.",
    errorMessage: "There was an error sending the message. Please try again.",
    whatsappText: "Prefer to contact us directly?",
    whatsappButton: "Write us on WhatsApp",
    whatsappMessage: "Hi! I saw your landing page and I'm interested in learning more about your services",
  },
};

export type LandingContent = typeof landingContentEs;
